### ISSUE TITLE
Hintergrund ändern PublicUI

### ISSUE THREAD

**Issue by mmock-uni** [mmock-uni/ThBw#547]
https://github.com/Linux249/ThBw/issues/422

**Comment by mmock-uni** [comment]
FONT-FAMILY: Helvetica Neue
Hintergrund-Farbe-Body: #EBE9E7
FOOTER-Farbe: #0063AD
HEADER-Farbe: #DCDCDC

**Comment by danieldegen** [comment]
Für die Hintergrundfarbe muss man in ScrollContainer.js folgenden Code einfügen:
`import { bodyGrey } from './colors';`
und
`background-color: ${bodyGrey};`

In Ansicht/Objekt sieht es dann gut aus, ohne dass man in der PublicViewHoc etwas ändern müsste. Dummer Nebeneffekt: Wirkt sich auch auf Edit aus, dort sieht es aber nicht (sofort) gut aus, wegen der ganzen Inputfelder.

**Comment by danieldegen** [comment]
da uns der Akademie-Header fehlt und unser Menü in `#DCDCDC` oder `#DDDDDD` nicht gut aussieht, ist hier in index.css unter body ebenfalls `#eceae8` (=bodyGrey) zu verwenden

**Comment by danieldegen** [comment]
![image](https://user-images.githubusercontent.com/33129404/55489798-ef9e6700-5632-11e9-90a8-8c3dfc947332.png)

**Comment by danieldegen** [comment]
eigentlich sieht es in der Edit auch nicht schlecht aus mit den weißen Inputs. Bloß die List simpels sehen schlecht aus:
![image](https://user-images.githubusercontent.com/33129404/55490002-46a43c00-5633-11e9-854d-c1d1287fc006.png)

**Comment by danieldegen** [comment]
Scrollcontainer ist doch nicht der richtige Ort um das zu ändern, man muss bloß bei colors.js unter background die gewünschte Farbe wählen

**Comment by danieldegen** [comment]
woran liegt das, dass das HTML im iFrame nur teilweise die Hintergrundfarbe übernimmt?:

![image](https://user-images.githubusercontent.com/33129404/55492345-5cb3fb80-5637-11e9-9712-3e56aa12f309.png)

**Comment by danieldegen** [comment]
ok ich habe das jetzt gepusht, wohl wissend, dass das erst deployed werden kann, wenn das mit dem IFrame gelöst ist und für Area noStyle sollte man auch noch eine Lösung finden. Aber ich rechne damit, dass meine commits so bleiben können.

**Comment by danieldegen** [comment]
jetzt bleibt nur noch das mit dem list simple (Area no style) zu lösen.
